#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 O.S. Systems Software LTDA.

# Ensure the environment has the required packages and prepare 'direnv' for execution.

die() {
    echo "ERROR: $@"
    exit 1
}

type direnv &> /dev/null || die "direnv is not available, aborting..."
type nix &> /dev/null || die "nix is not available, aborting..."

basedir=$(basename $(dirname $(dirname $(readlink -f $0))))
workspace_dir=$(dirname $(readlink -f $0))/../../

cat > $workspace_dir/.envrc <<EOF
if ! has nix_direnv_version || ! nix_direnv_version 2.2.0; then
  source_url "https://raw.githubusercontent.com/nix-community/nix-direnv/2.2.0/direnvrc" "sha256-5EwyKnkJNQeXrRkYbwwRBcXbibosCJqyIUuz9Xq+LRc="
fi

nix_direnv_watch_file \$(find . -name "*.nix" -printf '"%p" ')
use flake $basedir/
EOF

direnv allow
