# Copyright 2022 Freedom Veículos Elétricos LTDA.
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: zephyr-c++-api

      - uses: cachix/install-nix-action@v17

      - uses: cachix/cachix-action@v12
        with:
          name: freedom-zephyr-cpp-api
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Evaluate Nix Development Shell
        working-directory: zephyr-c++-api
        run: |
          # Does nothing but ensures we have a clear understand of time spent during download and
          # evaluation of the shell expression.
          nix develop

      - name: Check Code Formatting
        working-directory: zephyr-c++-api
        run: |
          nix develop -c bash <<EOF
            ./scripts/format-code

            if [ -n "$(git status --porcelain)" ]; then
                echo "ERROR: Code is not properly formatted"
                git diff
                exit 1
            fi
          EOF

      - name: Check License Headers
        working-directory: zephyr-c++-api
        run: |
          nix develop -c bash <<EOF
            ./scripts/license-headers

            if [ -n "$(git status --porcelain)" ]; then
                echo "ERROR: Code is not properly formatted"
                git diff
                exit 1
            fi
          EOF

      - name: Initialize
        working-directory: zephyr-c++-api
        run: |
          nix develop -c bash <<EOF
            west init -l .
            west update
          EOF

      - name: Twister Tests
        working-directory: zephyr-c++-api
        run: |
          nix develop -c bash <<EOF
            ./scripts/run-tests
          EOF
